"""Scan zones B/A in 30-degree steps, count unique pumpkins, and harvest.

Scan order:
    B: 0, -30, -60, -90, -120, -140 degrees
    return to 0
    A: 0, +30, +60, +90, +120, +140 degrees

The A/B pixel-to-robot homographies are converted to a common arm-local frame
and rotated with joint1. Detections closer than DUPLICATE_DISTANCE_M are merged,
so a pumpkin visible from adjacent views is counted once.

After scanning, every target is checked with non-moving inverse kinematics at
both approach and grasp heights. The old fixed 89.5-degree pitch is not used.
Actual harvesting begins only after the operator types HARVEST ALL.

Press Q in the video window or Ctrl-C to stop. Keep the mobile robot stationary
from the first camera frame until harvesting has finished.
"""

import json
import math
import time
from dataclasses import dataclass, field
from pathlib import Path

import cv2
import numpy as np
from ultralytics import YOLO

from omx_f import OmxFollower


# ---------------------------- Files and model ----------------------------
MODEL_PATH = Path(
    "/home/chaeyoung/KSAM/NILARM/src/vision_pkg/models/nil_pumpkin.pt"
)
TEST_DIR = Path(__file__).resolve().parent
VIEW_POSES_PATH = TEST_DIR / "pumpkin_ab_view_poses.json"
XY_CALIBRATION_PATH = TEST_DIR / "pumpkin_ab_grasp_xy_calibration.json"
PLANE_CALIBRATION_PATH = TEST_DIR / "pumpkin_plane_calibration.json"
BIN_POSE_PATH = TEST_DIR / "pumpkin_bin_pose.json"

CONFIDENCE = 0.70
YOLO_IMAGE_SIZE = 416
TARGET_CLASS_NAMES = {"nil_pumpkin", "pumpkin"}

# ------------------------------ Scan motion ------------------------------
B_SCAN_ANGLES_DEG = [0, -30, -60, -90, -120, -140]
A_SCAN_ANGLES_DEG = [0, 30, 60, 90, 120, 140]
JOINT1_SAFE_LIMIT_DEG = 145.0
SCAN_STEP_DURATION_SEC = 6.0
CENTER_RETURN_DURATION_SEC = 10.0
SETTLE_TIME_SEC = 2.0
VIEW_TIME_SEC = 6.0

# Detections within 5 cm are treated as the same physical pumpkin.
DUPLICATE_DISTANCE_M = 0.05
MIN_HITS = 4

# ----------------------------- Harvest motion ----------------------------
GRASP_PITCH_CANDIDATES_DEG = [80, 75, 70, 65, 60, 55, 50, 45]
APPROACH_DURATION_SEC = 8.0
DESCEND_DURATION_SEC = 5.0
LIFT_DURATION_SEC = 5.0
BIN_MOVE_DURATION_SEC = 8.0
GRIPPER_WAIT_SEC = 1.5
TRANSPORT_CLEARANCE_M = 0.05

WINDOW_NAME = "Pumpkin A/B scan - Q stop"


@dataclass
class Cluster:
    x: float
    y: float
    confidence: float
    hits: int = 1
    views: set[float] = field(default_factory=set)
    planned_pitch_rad: float | None = None

    def add(self, x, y, confidence, angle_deg):
        new_hits = self.hits + 1
        self.x = (self.x * self.hits + x) / new_hits
        self.y = (self.y * self.hits + y) / new_hits
        self.hits = new_hits
        self.confidence = max(self.confidence, confidence)
        self.views.add(float(angle_deg))


def normalize_name(value):
    return str(value).strip().lower()


def checked_array(value, shape, name):
    array = np.asarray(value, dtype=float)
    if array.shape != shape or not np.all(np.isfinite(array)):
        raise ValueError(f"{name} 값이 올바르지 않습니다: {array.shape}")
    return array


def load_json(path, description):
    if not path.is_file():
        raise FileNotFoundError(f"{description} 파일이 없습니다: {path}")
    return json.loads(path.read_text(encoding="utf-8"))


def load_settings():
    poses = load_json(VIEW_POSES_PATH, "A/B 촬영 자세")
    xy_data = load_json(XY_CALIBRATION_PATH, "A/B 그리퍼 XY 보정")
    plane = load_json(PLANE_CALIBRATION_PATH, "평면/높이 보정")
    bin_data = load_json(BIN_POSE_PATH, "정면 적재함 자세")

    camera = poses["camera"]
    zone_poses = {
        zone: checked_array(
            poses["zones"][zone]["joints_rad"],
            (5,),
            f"zones.{zone}.joints_rad",
        )
        for zone in ("A", "B")
    }

    # A was generated by changing only joint1, so joints 2-5 must match B.
    difference_deg = np.abs(
        np.degrees(zone_poses["A"][1:] - zone_poses["B"][1:])
    )
    if np.max(difference_deg) > 1.0:
        raise ValueError(
            "A/B 촬영 자세의 joint2~5가 서로 다릅니다. "
            "30도 스캔에서는 같은 카메라 기울기를 사용해야 합니다."
        )

    mappings = {}
    median_zone_y = {}
    for zone in ("A", "B"):
        zone_data = xy_data["zones"][zone]
        homography = checked_array(
            zone_data["homography_pixel_uv_to_robot_xy"],
            (3, 3),
            f"zones.{zone}.homography_pixel_uv_to_robot_xy",
        )
        records = zone_data.get("records", [])
        if len(records) < 4:
            raise ValueError(f"{zone} 구역 보정점이 4개보다 적습니다.")

        pixel_points = checked_array(
            [record["pixel_uv"] for record in records],
            (len(records), 2),
            f"zones.{zone}.records.pixel_uv",
        )
        actual_points = checked_array(
            [record["actual_xy_m"] for record in records],
            (len(records), 2),
            f"zones.{zone}.records.actual_xy_m",
        )
        mappings[zone] = {
            "homography": homography,
            "pixel_hull": cv2.convexHull(pixel_points.astype(np.float32)),
            "reference_joint1_deg": float(
                np.degrees(zone_poses[zone][0])
            ),
        }
        median_zone_y[zone] = float(np.median(actual_points[:, 1]))

    grasp = plane.get("grasp")
    if not isinstance(grasp, dict):
        raise ValueError("pumpkin_plane_calibration.json에 grasp 정보가 없습니다.")
    grasp_z = float(grasp["grasp_z_m"])
    approach_z = float(grasp["approach_z_m"])
    if not math.isfinite(grasp_z) or not math.isfinite(approach_z):
        raise ValueError("grasp_z_m 또는 approach_z_m이 유효하지 않습니다.")
    if approach_z <= grasp_z:
        raise ValueError("approach_z_m은 grasp_z_m보다 높아야 합니다.")

    bin_joints = checked_array(
        bin_data["bin_joints_rad"],
        (5,),
        "bin_joints_rad",
    )
    if abs(float(np.degrees(bin_joints[0]))) > 30.0:
        raise ValueError("적재함 자세의 joint1이 정면 -30~+30도 범위가 아닙니다.")

    # Determine the physical A/B side from the measured robot Y coordinates.
    a_is_positive_y = median_zone_y["A"] > median_zone_y["B"]

    neutral_joints = zone_poses["B"].copy()
    neutral_joints[0] = 0.0

    return {
        "camera_index": int(camera["index"]),
        "width": int(camera["width"]),
        "height": int(camera["height"]),
        "zone_poses": zone_poses,
        "neutral_joints": neutral_joints,
        "mappings": mappings,
        "a_is_positive_y": a_is_positive_y,
        "grasp_z": grasp_z,
        "approach_z": approach_z,
        "bin_joints": bin_joints,
    }


def open_camera(settings):
    cap = cv2.VideoCapture(settings["camera_index"], cv2.CAP_V4L2)
    cap.set(cv2.CAP_PROP_FOURCC, cv2.VideoWriter_fourcc(*"MJPG"))
    cap.set(cv2.CAP_PROP_FRAME_WIDTH, settings["width"])
    cap.set(cv2.CAP_PROP_FRAME_HEIGHT, settings["height"])
    cap.set(cv2.CAP_PROP_BUFFERSIZE, 1)
    if not cap.isOpened():
        raise RuntimeError(
            f"카메라 /dev/video{settings['camera_index']}를 열 수 없습니다."
        )
    for _ in range(8):
        cap.read()
    return cap


def validate_model(model):
    names = model.names.values() if isinstance(model.names, dict) else model.names
    available = {normalize_name(name) for name in names}
    if not available.intersection(TARGET_CLASS_NAMES):
        raise ValueError(
            "모델 클래스에 nil_pumpkin 또는 pumpkin이 없습니다. "
            f"model.names={model.names}"
        )


def rotate_xy(x, y, angle_deg):
    angle = math.radians(float(angle_deg))
    cosine = math.cos(angle)
    sine = math.sin(angle)
    return cosine * x - sine * y, sine * x + cosine * y


def homography_xy(u, v, homography):
    mapped = homography @ np.asarray([u, v, 1.0], dtype=float)
    denominator = float(mapped[2])
    if abs(denominator) < 1e-9:
        raise ValueError("픽셀 좌표 변환 분모가 0에 가깝습니다.")
    x = float(mapped[0] / denominator)
    y = float(mapped[1] / denominator)
    if not math.isfinite(x) or not math.isfinite(y):
        raise ValueError("픽셀 변환 결과가 유효하지 않습니다.")
    return x, y


def pixel_inside_hull(u, v, hull):
    return cv2.pointPolygonTest(hull, (float(u), float(v)), False) >= 0


def local_xy_from_reference(u, v, mapping):
    if not pixel_inside_hull(u, v, mapping["pixel_hull"]):
        return None
    world_x, world_y = homography_xy(u, v, mapping["homography"])
    return rotate_xy(
        world_x,
        world_y,
        -mapping["reference_joint1_deg"],
    )


def pixel_to_world_xy(u, v, joint1_deg, mappings):
    """Map a pixel at any scan angle using the nearest calibrated side."""
    if joint1_deg < -1e-6:
        zone_order = ("B", "A")
    elif joint1_deg > 1e-6:
        zone_order = ("A", "B")
    else:
        zone_order = ("A", "B")

    local_candidates = []
    for zone in zone_order:
        local_xy = local_xy_from_reference(u, v, mappings[zone])
        if local_xy is not None:
            local_candidates.append(local_xy)
            # Away from zero, prefer the calibration from the same side.
            if abs(joint1_deg) > 1e-6:
                break

    if not local_candidates:
        return None

    local_x = float(np.mean([point[0] for point in local_candidates]))
    local_y = float(np.mean([point[1] for point in local_candidates]))
    return rotate_xy(local_x, local_y, joint1_deg)


def zone_for_xy(y, settings):
    if settings["a_is_positive_y"]:
        return "A" if y >= 0.0 else "B"
    return "A" if y <= 0.0 else "B"


def add_detection(clusters, x, y, confidence, angle_deg):
    nearest = None
    nearest_distance = float("inf")
    for cluster in clusters:
        distance = math.hypot(cluster.x - x, cluster.y - y)
        if distance < nearest_distance:
            nearest = cluster
            nearest_distance = distance

    if nearest is not None and nearest_distance <= DUPLICATE_DISTANCE_M:
        nearest.add(x, y, confidence, angle_deg)
    else:
        clusters.append(
            Cluster(
                x=x,
                y=y,
                confidence=confidence,
                views={float(angle_deg)},
            )
        )


def valid_clusters(clusters):
    return [cluster for cluster in clusters if cluster.hits >= MIN_HITS]


def detect_frame(model, frame, joint1_deg, settings):
    result = model.predict(
        source=frame,
        conf=CONFIDENCE,
        imgsz=YOLO_IMAGE_SIZE,
        device="cpu",
        verbose=False,
    )[0]
    detections = []

    for box in result.boxes:
        class_id = int(box.cls[0].item())
        class_name = normalize_name(model.names[class_id])
        confidence = float(box.conf[0].item())
        if class_name not in TARGET_CLASS_NAMES or confidence < CONFIDENCE:
            continue

        x1, y1, x2, y2 = [float(value) for value in box.xyxy[0].tolist()]
        u = (x1 + x2) / 2.0
        v = (y1 + y2) / 2.0
        world_xy = pixel_to_world_xy(
            u,
            v,
            joint1_deg,
            settings["mappings"],
        )
        if world_xy is None:
            continue

        detections.append(
            {
                "u": u,
                "v": v,
                "x": world_xy[0],
                "y": world_xy[1],
                "confidence": confidence,
            }
        )

    return result, detections


def observe_view(model, cap, angle_deg, clusters, settings):
    deadline = time.monotonic() + VIEW_TIME_SEC
    local_clusters = []

    for _ in range(5):
        cap.read()

    while time.monotonic() < deadline:
        ok, frame = cap.read()
        if not ok or frame is None:
            raise RuntimeError("카메라 프레임을 읽지 못했습니다.")

        result, detections = detect_frame(model, frame, angle_deg, settings)
        for detection in detections:
            add_detection(
                local_clusters,
                detection["x"],
                detection["y"],
                detection["confidence"],
                angle_deg,
            )
            add_detection(
                clusters,
                detection["x"],
                detection["y"],
                detection["confidence"],
                angle_deg,
            )

        current = valid_clusters(clusters)
        a_count = sum(
            zone_for_xy(cluster.y, settings) == "A" for cluster in current
        )
        b_count = sum(
            zone_for_xy(cluster.y, settings) == "B" for cluster in current
        )

        # YOLO pumpkin boxes remain visible; no mint calibration outline.
        annotated = result.plot()
        cv2.putText(
            annotated,
            f"Joint1: {angle_deg:+.0f} deg",
            (15, 32),
            cv2.FONT_HERSHEY_SIMPLEX,
            0.75,
            (255, 255, 255),
            2,
        )
        cv2.putText(
            annotated,
            f"A-{a_count} / B-{b_count}",
            (15, 68),
            cv2.FONT_HERSHEY_SIMPLEX,
            0.8,
            (0, 255, 255),
            2,
        )
        cv2.putText(
            annotated,
            "Q: stop and park",
            (15, annotated.shape[0] - 18),
            cv2.FONT_HERSHEY_SIMPLEX,
            0.58,
            (0, 0, 255),
            2,
        )
        cv2.imshow(WINDOW_NAME, annotated)

        key = cv2.waitKey(1) & 0xFF
        if key in (ord("q"), ord("Q")):
            return True
        try:
            if cv2.getWindowProperty(WINDOW_NAME, cv2.WND_PROP_VISIBLE) < 1:
                return True
        except cv2.error:
            return True

    return False


def move_to_scan_angle(arm, neutral_joints, angle_deg, duration):
    if abs(float(angle_deg)) > JOINT1_SAFE_LIMIT_DEG:
        raise ValueError(f"joint1={angle_deg:.1f}도가 안전 범위 밖입니다.")
    target = neutral_joints.copy()
    target[0] = math.radians(float(angle_deg))
    print(f"[스캔 이동] joint1={angle_deg:+.0f}도, {duration:.1f}초")
    arm.move_joints(target, duration=duration)
    time.sleep(SETTLE_TIME_SEC)


def scan_all_views(arm, model, cap, settings):
    clusters = []
    stop = False

    print("\n[B 구역 스캔] 0도에서 -140도 방향")
    current_angle = 0.0
    for angle in B_SCAN_ANGLES_DEG:
        duration = (
            5.0 if angle == 0 else SCAN_STEP_DURATION_SEC
        )
        move_to_scan_angle(
            arm,
            settings["neutral_joints"],
            angle,
            duration,
        )
        current_angle = float(angle)
        stop = observe_view(model, cap, angle, clusters, settings)
        if stop:
            return clusters, True

    print("\n[중앙 복귀] A 구역 스캔을 위해 0도로 돌아갑니다.")
    move_to_scan_angle(
        arm,
        settings["neutral_joints"],
        0.0,
        CENTER_RETURN_DURATION_SEC,
    )
    current_angle = 0.0

    print("\n[A 구역 스캔] 0도에서 +140도 방향")
    for angle in A_SCAN_ANGLES_DEG:
        # The center view is intentionally observed again; global coordinate
        # clustering prevents double counting.
        duration = 1.0 if angle == 0 else SCAN_STEP_DURATION_SEC
        if angle != 0:
            move_to_scan_angle(
                arm,
                settings["neutral_joints"],
                angle,
                duration,
            )
            current_angle = float(angle)
        stop = observe_view(model, cap, angle, clusters, settings)
        if stop:
            return clusters, True

    return clusters, False


def summarize_targets(clusters, settings):
    targets = sorted(
        valid_clusters(clusters),
        key=lambda cluster: math.hypot(cluster.x, cluster.y),
    )
    a_targets = [
        target for target in targets
        if zone_for_xy(target.y, settings) == "A"
    ]
    b_targets = [
        target for target in targets
        if zone_for_xy(target.y, settings) == "B"
    ]

    print("\n========== A/B 호박 스캔 결과 ==========")
    print(f"A-{len(a_targets)} / B-{len(b_targets)}")
    for index, target in enumerate(targets, start=1):
        zone = zone_for_xy(target.y, settings)
        views = sorted(target.views)
        print(
            f"{index:02d}. {zone}구역 xy=({target.x:.3f}, {target.y:.3f}) m, "
            f"conf={target.confidence:.2f}, views={views}"
        )
    print("==========================================")
    return targets


def solve_ik(arm, xyz, seed_joints, pitch_rad):
    kin = getattr(arm, "kin", None)
    inverse = getattr(kin, "inverse", None)
    if not callable(inverse):
        raise RuntimeError(
            "omx_f에서 비동작 역기구학 arm.kin.inverse를 찾지 못했습니다. "
            "실제 이동으로 pitch를 시험하지 않고 수확을 중단합니다."
        )
    solution = np.asarray(
        inverse(
            tuple(float(value) for value in xyz),
            np.asarray(seed_joints, dtype=float),
            pitch=float(pitch_rad),
            roll=0.0,
        ),
        dtype=float,
    )
    if solution.shape != (5,) or not np.all(np.isfinite(solution)):
        raise ValueError("역기구학 결과가 올바른 5개 관절각이 아닙니다.")
    return solution


def select_reachable_pitch(arm, target, settings, seed_joints):
    x = float(target.x)
    y = float(target.y)
    approach_z = settings["approach_z"]
    grasp_z = settings["grasp_z"]
    transport_z = approach_z + TRANSPORT_CLEARANCE_M

    print(
        f"\n[IK 검사] xy=({x:.3f}, {y:.3f}) m, "
        f"approach={approach_z:.3f}, grasp={grasp_z:.3f}"
    )
    for pitch_deg in GRASP_PITCH_CANDIDATES_DEG:
        pitch_rad = math.radians(float(pitch_deg))
        try:
            approach_q = solve_ik(
                arm,
                (x, y, approach_z),
                seed_joints,
                pitch_rad,
            )
            grasp_q = solve_ik(
                arm,
                (x, y, grasp_z),
                approach_q,
                pitch_rad,
            )
            solve_ik(
                arm,
                (x, y, transport_z),
                grasp_q,
                pitch_rad,
            )
        except (ValueError, RuntimeError) as error:
            print(f"  pitch {pitch_deg:>4.0f}도: 불가능 ({error})")
            continue

        print(f"  pitch {pitch_deg:>4.0f}도: 접근/하강/상승 가능")
        return pitch_rad

    raise ValueError(
        f"xy=({x:.3f}, {y:.3f})에서 가능한 집기 pitch가 없습니다."
    )


def preflight_all_targets(arm, targets, settings):
    seed_joints = np.asarray(arm.joints(), dtype=float).copy()
    for target in targets:
        target.planned_pitch_rad = select_reachable_pitch(
            arm,
            target,
            settings,
            seed_joints,
        )


def move_linear_or_to(arm, x, y, z, duration, pitch):
    move_linear = getattr(arm, "move_linear", None)
    if callable(move_linear):
        return move_linear(
            x,
            y,
            z,
            duration=duration,
            pitch=pitch,
            roll=0.0,
        )
    return arm.move_to(
        x,
        y,
        z,
        duration=duration,
        pitch=pitch,
        roll=0.0,
    )


def harvest_one(arm, target, settings, motion_state):
    x = float(target.x)
    y = float(target.y)
    pitch = target.planned_pitch_rad
    if pitch is None:
        raise RuntimeError("목표의 집기 pitch가 계획되지 않았습니다.")

    print("[수확] 그리퍼를 엽니다.")
    arm.open_gripper()
    time.sleep(GRIPPER_WAIT_SEC)

    print(
        f"[수확] 접근: x={x:.3f}, y={y:.3f}, "
        f"z={settings['approach_z']:.3f}, "
        f"pitch={math.degrees(pitch):.1f}도"
    )
    arm.move_to(
        x,
        y,
        settings["approach_z"],
        duration=APPROACH_DURATION_SEC,
        pitch=pitch,
        roll=0.0,
    )

    print(f"[수확] 잡기 높이 z={settings['grasp_z']:.3f} m로 하강합니다.")
    move_linear_or_to(
        arm,
        x,
        y,
        settings["grasp_z"],
        DESCEND_DURATION_SEC,
        pitch,
    )

    print("[수확] 그리퍼를 닫습니다.")
    arm.close_gripper()
    motion_state["holding"] = True
    motion_state["last_target"] = (x, y, pitch)
    time.sleep(GRIPPER_WAIT_SEC)

    transport_z = settings["approach_z"] + TRANSPORT_CLEARANCE_M
    print(f"[수확] 운반 높이 z={transport_z:.3f} m로 상승합니다.")
    move_linear_or_to(
        arm,
        x,
        y,
        transport_z,
        LIFT_DURATION_SEC,
        pitch,
    )


def deposit_in_bin(arm, settings, motion_state):
    print("[적재] 저장된 정면 바구니 자세로 이동합니다.")
    arm.move_joints(settings["bin_joints"], duration=BIN_MOVE_DURATION_SEC)
    time.sleep(0.7)
    print("[적재] 그리퍼를 열어 호박을 놓습니다.")
    arm.open_gripper()
    motion_state["holding"] = False
    motion_state["last_target"] = None
    time.sleep(GRIPPER_WAIT_SEC)

    print("[적재] 다음 목표를 위해 중앙 자세로 돌아갑니다.")
    arm.move_joints(
        settings["neutral_joints"],
        duration=BIN_MOVE_DURATION_SEC,
    )
    time.sleep(SETTLE_TIME_SEC)


def emergency_release_if_holding(arm, settings, motion_state):
    if not motion_state["holding"]:
        return
    print(
        "경고: 호박을 잡은 상태입니다. 호박을 손으로 받치고 "
        "Enter를 누르세요."
    )
    try:
        input()
    except (EOFError, KeyboardInterrupt):
        pass
    try:
        arm.open_gripper()
        motion_state["holding"] = False
        time.sleep(GRIPPER_WAIT_SEC)
    except Exception as error:
        print(f"그리퍼 비상 열기 실패: {error}")


def main():
    arm = None
    cap = None
    settings = None
    motion_state = {"holding": False, "last_target": None}

    try:
        if not MODEL_PATH.is_file():
            raise FileNotFoundError(f"YOLO 모델이 없습니다: {MODEL_PATH}")

        settings = load_settings()
        model = YOLO(str(MODEL_PATH))
        validate_model(model)
        print("YOLO 클래스:", model.names)
        print(
            "A/B 좌표축 판정:",
            "A=+Y, B=-Y" if settings["a_is_positive_y"] else "A=-Y, B=+Y",
        )

        cap = open_camera(settings)
        print("OMX 로봇팔에 연결합니다.")
        arm = OmxFollower().connect()
        arm.ready(duration=5.0)

        print("중앙 0도 촬영 자세로 이동합니다.")
        arm.move_joints(settings["neutral_joints"], duration=8.0)
        time.sleep(SETTLE_TIME_SEC)

        clusters, stopped = scan_all_views(
            arm,
            model,
            cap,
            settings,
        )
        targets = summarize_targets(clusters, settings)

        cap.release()
        cap = None
        cv2.destroyAllWindows()

        if stopped:
            print("사용자가 스캔을 중단했으므로 수확하지 않습니다.")
            return
        if not targets:
            print("유효한 호박이 없어 수확하지 않습니다.")
            return

        print("수확 계획 전 중앙 자세로 돌아갑니다.")
        arm.move_joints(settings["neutral_joints"], duration=10.0)
        time.sleep(SETTLE_TIME_SEC)

        # No motor movement occurs in this preflight calculation.
        preflight_all_targets(arm, targets, settings)

        print("\n========== 수확 계획 ==========")
        for index, target in enumerate(targets, start=1):
            zone = zone_for_xy(target.y, settings)
            print(
                f"{index:02d}. {zone} xy=({target.x:.3f}, {target.y:.3f}) m, "
                f"pitch={math.degrees(target.planned_pitch_rad):.1f}도"
            )
        print(f"접근 z={settings['approach_z']:.3f} m")
        print(f"잡기 z={settings['grasp_z']:.3f} m")
        print("================================")
        print("이동로봇 본체를 움직이지 마세요.")
        print("사람, 케이블, 노트북을 로봇팔 작업범위 밖으로 치우세요.")

        confirmation = input(
            f"호박 {len(targets)}개를 수확하여 바구니에 넣으려면 "
            "HARVEST ALL 입력: "
        ).strip()
        if confirmation != "HARVEST ALL":
            print("수확을 취소했습니다.")
            return

        completed = 0
        for index, target in enumerate(targets, start=1):
            zone = zone_for_xy(target.y, settings)
            print(
                f"\n========== {index}/{len(targets)} "
                f"{zone}구역 호박 수확 =========="
            )
            harvest_one(arm, target, settings, motion_state)
            deposit_in_bin(arm, settings, motion_state)
            completed += 1
            print(f"[완료] 적재된 호박: {completed}/{len(targets)}")

        print(f"\n전체 수확과 적재가 끝났습니다: {completed}개")

    except KeyboardInterrupt:
        print("\n사용자가 동작을 중단했습니다.")
    except (FileNotFoundError, KeyError, TypeError, ValueError, RuntimeError) as error:
        print(f"\n[중단] {error}")
    finally:
        if cap is not None:
            cap.release()
        cv2.destroyAllWindows()

        if arm is not None:
            emergency_release_if_holding(
                arm,
                settings,
                motion_state,
            )
            if settings is not None:
                try:
                    print("중앙 촬영 자세로 돌아갑니다.")
                    arm.move_joints(
                        settings["neutral_joints"],
                        duration=10.0,
                    )
                except Exception as error:
                    print(f"중앙 자세 복귀 실패: {error}")
            try:
                print("정리 자세로 이동합니다.")
                arm.park()
            except Exception as error:
                print(f"park 실패: {error}")
            finally:
                arm.disconnect()
                print("로봇팔 연결을 종료했습니다.")


if __name__ == "__main__":
    main()
